### ISSUE TITLE
Roadmap to construct an API that returns roi_olist

### ISSUE THREAD

**Issue by pauloestrella1994** [pauloestrella1994/roi-olist#1]
- [x] Create a repository in github;
- [x] Create a directory and clone the project;
- [x] Create a virtual enviroment;
- [x] Add a generic README and add folders and files in .gitignore;
- [x] Upgrade pip;
- [x] Install Django, djangorestframework, psycopg2-binary;
- [x] Start project and apps with django-admin commands;
- [x] Configure settings, migrate and test runserver;
- [x] Create models and apply migrations;
- [x] Create a super user;
- [x] Populate data into the django admin forms;
- [x] Create a Serializer;
- [x] Create a Viewsets;
- [x] Create  a list of urls;
- [x] Test http verbs in insomnia or postman;
- [x] Create a Token Auth;
- [x] Generic review and fixings;
- [x] Deploy in Heroku;
- [x] Populate database;
- [x] Generic review and fixings;
